// ─── GRADIENT CONTROLS — SixDX ───────────────────────────────────────────────
// Floating live-edit panel for the WebGL gradient.
//
// [GL] button   — fixed bottom-right, click to open/close the panel
// Live edits    — saved to localStorage instantly (survive page refresh)
// Save to file  — downloads gradient.config.ts; drop it into
//                 src/components/ui/ and Vite reloads with new defaults
// Reset         — reverts everything to factory defaults
// ─────────────────────────────────────────────────────────────────────────────

import { useState } from 'react'
import type { GradientConfig } from './GradientCanvas'
import { DEFAULT_GRADIENT_CONFIG } from './GradientCanvas'
import { PRESET_GRADIENT_CONFIG } from './gradient.config'

// ─── STORAGE ──────────────────────────────────────────────────────────────────

const STORAGE_KEY = 'sixdx:gradient'

/**
 * Load order:
 *  1. localStorage  (in-session live edits — survives page refresh)
 *  2. PRESET_GRADIENT_CONFIG  (the saved .ts file)
 *  3. DEFAULT_GRADIENT_CONFIG (factory fallback for any missing keys)
 */
export function loadGradientConfig(): GradientConfig {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const saved = JSON.parse(raw) as Partial<GradientConfig>
      return {
        ...DEFAULT_GRADIENT_CONFIG,
        ...PRESET_GRADIENT_CONFIG,
        ...saved,
        colors: { ...DEFAULT_GRADIENT_CONFIG.colors, ...PRESET_GRADIENT_CONFIG.colors, ...(saved.colors ?? {}) },
        blends: { ...DEFAULT_GRADIENT_CONFIG.blends, ...PRESET_GRADIENT_CONFIG.blends, ...(saved.blends ?? {}) },
        ripple: { ...DEFAULT_GRADIENT_CONFIG.ripple, ...PRESET_GRADIENT_CONFIG.ripple, ...(saved.ripple ?? {}) },
        rays:   { ...DEFAULT_GRADIENT_CONFIG.rays,   ...PRESET_GRADIENT_CONFIG.rays,   ...(saved.rays   ?? {}) },
      }
    }
  } catch { /* ignore */ }
  // No localStorage → use the file preset (with factory keys as safety net)
  return {
    ...DEFAULT_GRADIENT_CONFIG,
    ...PRESET_GRADIENT_CONFIG,
    colors: { ...DEFAULT_GRADIENT_CONFIG.colors, ...PRESET_GRADIENT_CONFIG.colors },
    blends: { ...DEFAULT_GRADIENT_CONFIG.blends, ...PRESET_GRADIENT_CONFIG.blends },
    ripple: { ...DEFAULT_GRADIENT_CONFIG.ripple, ...PRESET_GRADIENT_CONFIG.ripple },
    rays:   { ...DEFAULT_GRADIENT_CONFIG.rays,   ...PRESET_GRADIENT_CONFIG.rays   },
  }
}

export function saveGradientConfig(cfg: GradientConfig) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(cfg)) } catch { /* ignore */ }
}

// ─── FILE EXPORT ──────────────────────────────────────────────────────────────

function generateConfigFileContent(cfg: GradientConfig): string {
  const date = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  // Pretty-print the config as valid TypeScript
  const json = JSON.stringify(cfg, null, 2)
  return `// ─── GRADIENT PRESET — SixDX ─────────────────────────────────────────────────
// Auto-generated by the [GL] control panel · ${date}
//
// To update:
//   1. Open the project in the browser  (npm run dev)
//   2. Click the [GL] button in the bottom-right corner
//   3. Dial in your effects
//   4. Click "💾 Save to file" inside the panel
//   5. A file called  gradient.config.ts  will download
//   6. Replace  src/components/ui/gradient.config.ts  with the downloaded file
//   7. Vite hot-reloads — your settings are now the project defaults
// ─────────────────────────────────────────────────────────────────────────────
import type { GradientConfig } from './GradientCanvas'

export const PRESET_GRADIENT_CONFIG: GradientConfig = ${json}
`
}

function downloadConfigFile(cfg: GradientConfig) {
  const content = generateConfigFileContent(cfg)
  const blob    = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url     = URL.createObjectURL(blob)
  const a       = document.createElement('a')
  a.href        = url
  a.download    = 'gradient.config.ts'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
  // Clear localStorage so the downloaded file becomes the source of truth on next load
  try { localStorage.removeItem(STORAGE_KEY) } catch { /* ignore */ }
}

// ─── DESIGN ───────────────────────────────────────────────────────────────────

const D = {
  bg:              '#0F0705',
  border:          'rgba(204, 77, 34, 0.25)',
  accent:          '#CC4D22',
  accentDim:       'rgba(204, 77, 34, 0.18)',
  text:            '#F5EDE8',
  muted:           'rgba(245, 237, 232, 0.45)',
  inputBg:         'rgba(255,255,255,0.05)',
  green:           '#4CAF50',
  radius:          3,
  font:            'HelveticaNeue, "Helvetica Neue", Helvetica, sans-serif',
  panelW:          300,
  transitionSpeed: '0.25s',
} as const

// ─── MICRO COMPONENTS ─────────────────────────────────────────────────────────

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <p style={{
      fontFamily: D.font, fontSize: 9, fontWeight: 600,
      letterSpacing: '0.12em', textTransform: 'uppercase',
      color: D.accent, margin: '16px 0 8px',
      padding: '0 0 6px', borderBottom: `1px solid ${D.border}`,
    }}>
      {children}
    </p>
  )
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
      <span style={{
        fontFamily: D.font, fontSize: 11, color: D.muted,
        flexShrink: 0, width: 82, lineHeight: 1,
      }}>
        {label}
      </span>
      {children}
    </div>
  )
}

function Slider({
  value, min, max, step = 0.01, onChange,
}: { value: number; min: number; max: number; step?: number; onChange: (v: number) => void }) {
  return (
    <div style={{ flex: 1, display: 'flex', alignItems: 'center', gap: 7 }}>
      <input
        type="range" min={min} max={max} step={step} value={value}
        onChange={e => onChange(parseFloat(e.target.value))}
        style={{ flex: 1, height: 3, accentColor: D.accent, cursor: 'pointer', background: 'transparent' }}
      />
      <span style={{
        fontFamily: D.font, fontSize: 10, color: D.text,
        width: 36, textAlign: 'right', flexShrink: 0, fontVariantNumeric: 'tabular-nums',
      }}>
        {Math.abs(value) < 10 ? value.toFixed(2) : value.toFixed(1)}
      </span>
    </div>
  )
}

function IntSlider({
  value, min, max, onChange,
}: { value: number; min: number; max: number; onChange: (v: number) => void }) {
  return (
    <div style={{ flex: 1, display: 'flex', alignItems: 'center', gap: 7 }}>
      <input
        type="range" min={min} max={max} step={1} value={value}
        onChange={e => onChange(parseInt(e.target.value, 10))}
        style={{ flex: 1, height: 3, accentColor: D.accent, cursor: 'pointer', background: 'transparent' }}
      />
      <span style={{
        fontFamily: D.font, fontSize: 10, color: D.text,
        width: 24, textAlign: 'right', flexShrink: 0, fontVariantNumeric: 'tabular-nums',
      }}>
        {value}
      </span>
    </div>
  )
}

function Toggle({ value, onChange }: { value: boolean; onChange: (v: boolean) => void }) {
  return (
    <button
      onClick={() => onChange(!value)}
      style={{
        flex: 1, height: 20, borderRadius: D.radius, cursor: 'pointer',
        border:     `1px solid ${value ? D.accent : 'rgba(245,237,232,0.2)'}`,
        background: value ? 'rgba(204,77,34,0.25)' : D.inputBg,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        transition: `background ${D.transitionSpeed}, border-color ${D.transitionSpeed}`,
      }}
    >
      <span style={{
        fontFamily: D.font, fontSize: 9, fontWeight: 600,
        letterSpacing: '0.1em', textTransform: 'uppercase',
        color: value ? D.accent : D.muted,
      }}>
        {value ? 'ON' : 'OFF'}
      </span>
    </button>
  )
}

/** Segmented 4-way blend mode selector in a 2×2 grid */
function BlendMode({ value, onChange }: { value: number; onChange: (v: number) => void }) {
  const modes = ['Add', 'Screen', 'Overlay', '+Light']
  return (
    <div style={{ flex: 1, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 2 }}>
      {modes.map((m, i) => (
        <button
          key={m}
          onClick={() => onChange(i)}
          style={{
            padding: '4px 0',
            fontFamily: D.font, fontSize: 9, fontWeight: 600,
            letterSpacing: '0.06em', textTransform: 'uppercase',
            cursor: 'pointer', borderRadius: D.radius,
            background: value === i ? 'rgba(204,77,34,0.28)' : D.inputBg,
            border:     `1px solid ${value === i ? D.accent : 'rgba(245,237,232,0.15)'}`,
            color:      value === i ? D.accent : D.muted,
            transition: `background ${D.transitionSpeed}, border-color ${D.transitionSpeed}`,
          }}
        >
          {m}
        </button>
      ))}
    </div>
  )
}

function ColorSwatch({ label, value, onChange }: { label: string; value: string; onChange: (v: string) => void }) {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
      <label style={{ position: 'relative', cursor: 'pointer', flexShrink: 0 }}>
        <div style={{
          width: 22, height: 22, borderRadius: D.radius,
          background: value, border: '1px solid rgba(255,255,255,0.15)',
        }} />
        <input
          type="color" value={value} onChange={e => onChange(e.target.value)}
          style={{ position: 'absolute', inset: 0, opacity: 0, width: '100%', height: '100%', cursor: 'pointer', border: 'none', padding: 0 }}
        />
      </label>
      <span style={{ fontFamily: D.font, fontSize: 11, color: D.muted, flexShrink: 0, width: 60 }}>{label}</span>
      <span style={{ fontFamily: D.font, fontSize: 10, color: D.text, letterSpacing: '0.05em' }}>{value.toUpperCase()}</span>
    </div>
  )
}

function BlendRow({ label, value, onChange }: { label: string; value: [number, number]; onChange: (v: [number, number]) => void }) {
  return (
    <div style={{ marginBottom: 8 }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
        <span style={{ fontFamily: D.font, fontSize: 10, color: D.muted }}>{label}</span>
        <span style={{ fontFamily: D.font, fontSize: 10, color: D.text, fontVariantNumeric: 'tabular-nums' }}>
          {value[0].toFixed(2)} → {value[1].toFixed(2)}
        </span>
      </div>
      <div style={{ display: 'flex', gap: 6 }}>
        <input type="range" min={0} max={1} step={0.01} value={value[0]}
          onChange={e => onChange([parseFloat(e.target.value), value[1]])}
          style={{ flex: 1, height: 3, accentColor: D.accent, cursor: 'pointer' }}
        />
        <input type="range" min={0} max={1} step={0.01} value={value[1]}
          onChange={e => onChange([value[0], parseFloat(e.target.value)])}
          style={{ flex: 1, height: 3, accentColor: 'rgba(204,77,34,0.5)', cursor: 'pointer' }}
        />
      </div>
    </div>
  )
}

// ─── PROPS ────────────────────────────────────────────────────────────────────

export interface GradientControlsProps {
  config:   GradientConfig
  onChange: (next: GradientConfig) => void
}

// ─── COMPONENT ────────────────────────────────────────────────────────────────

export default function GradientControls({ config, onChange }: GradientControlsProps) {
  const [open,    setOpen]    = useState(false)
  const [saved,   setSaved]   = useState(false)   // brief "Saved!" feedback

  // ── Updater helpers ──────────────────────────────────────────────────────
  const set = (patch: Partial<GradientConfig>) => {
    const next = { ...config, ...patch }; onChange(next); saveGradientConfig(next)
  }
  const setColor  = (key: keyof GradientConfig['colors'], v: string) =>
    set({ colors: { ...config.colors,  [key]: v } })
  const setBlend  = (key: keyof GradientConfig['blends'], v: [number, number]) =>
    set({ blends: { ...config.blends,  [key]: v } })
  const setRipple = (patch: Partial<GradientConfig['ripple']>) =>
    set({ ripple: { ...config.ripple, ...patch } })
  const setRays   = (patch: Partial<GradientConfig['rays']>) =>
    set({ rays:   { ...config.rays,   ...patch } })

  const reset = () => {
    const next = { ...DEFAULT_GRADIENT_CONFIG }; onChange(next); saveGradientConfig(next)
  }

  const handleSaveToFile = () => {
    downloadConfigFile(config)
    setSaved(true)
    setTimeout(() => setSaved(false), 2500)
  }

  return (
    <>
      {/* ── [GL] toggle pill — fixed bottom-right ────────────────────────── */}
      <button
        onClick={() => setOpen(o => !o)}
        title={open ? 'Close gradient controls' : 'Open gradient controls'}
        style={{
          position: 'fixed', bottom: 24, right: 24, zIndex: 10000,
          background: open ? D.accent : D.bg,
          border: `1px solid ${D.accent}`, borderRadius: D.radius,
          cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
          padding: '6px 12px', transition: `background ${D.transitionSpeed}`,
        }}
      >
        <div style={{
          width: 8, height: 8, borderRadius: '50%', flexShrink: 0,
          background: `linear-gradient(135deg, ${config.colors.orange}, ${config.colors.sienna})`,
        }} />
        <span style={{ fontFamily: D.font, fontSize: 11, fontWeight: 600, letterSpacing: '0.08em', color: D.text }}>
          GL
        </span>
      </button>

      {/* ── Panel ────────────────────────────────────────────────────────── */}
      <div style={{
        position: 'fixed', bottom: 68, right: 24, zIndex: 9999,
        width: D.panelW, background: D.bg,
        border: `1px solid ${D.border}`, borderRadius: D.radius, overflow: 'hidden',
        opacity:       open ? 1 : 0,
        transform:     open ? 'translateY(0)' : 'translateY(12px)',
        pointerEvents: open ? 'auto' : 'none',
        transition:    `opacity ${D.transitionSpeed} ease, transform ${D.transitionSpeed} ease`,
        boxShadow:     '0 8px 40px rgba(0,0,0,0.6)',
      }}>

        {/* ── Panel header ─────────────────────────────────────────────── */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '10px 14px', borderBottom: `1px solid ${D.border}`,
        }}>
          <span style={{ fontFamily: D.font, fontSize: 11, fontWeight: 600, color: D.text, letterSpacing: '0.04em' }}>
            Gradient Controls
          </span>
          <button onClick={reset} style={{
            fontFamily: D.font, fontSize: 10, color: D.muted,
            background: 'none', border: 'none', cursor: 'pointer',
            padding: '2px 6px', borderRadius: D.radius, letterSpacing: '0.04em',
          }}>
            Reset defaults
          </button>
        </div>

        {/* ── Scrollable body ──────────────────────────────────────────── */}
        <div style={{ padding: '4px 14px 8px', maxHeight: '68vh', overflowY: 'auto' }}>

          {/* MOTION */}
          <SectionLabel>Motion</SectionLabel>
          <Row label="Speed">
            <Slider value={config.speed} min={0.05} max={3} step={0.05} onChange={v => set({ speed: v })} />
          </Row>
          <Row label="Warp scale">
            <Slider value={config.warpScale} min={0.5} max={8} step={0.1} onChange={v => set({ warpScale: v })} />
          </Row>

          {/* ATMOSPHERE */}
          <SectionLabel>Atmosphere</SectionLabel>
          <Row label="Vignette">
            <Slider value={config.vignette} min={0} max={1} onChange={v => set({ vignette: v })} />
          </Row>
          <Row label="Grain">
            <Slider value={config.grain} min={0} max={0.08} step={0.001} onChange={v => set({ grain: v })} />
          </Row>

          {/* PALETTE */}
          <SectionLabel>Palette</SectionLabel>
          <ColorSwatch label="Ink"    value={config.colors.ink}    onChange={v => setColor('ink', v)} />
          <ColorSwatch label="Orange" value={config.colors.orange} onChange={v => setColor('orange', v)} />
          <ColorSwatch label="Sienna" value={config.colors.sienna} onChange={v => setColor('sienna', v)} />
          <ColorSwatch label="Black"  value={config.colors.black}  onChange={v => setColor('black', v)} />

          {/* BLEND ZONES */}
          <SectionLabel>Blend zones</SectionLabel>
          <p style={{ fontFamily: D.font, fontSize: 10, color: D.muted, marginBottom: 10, lineHeight: 1.5 }}>
            Left = zone start · Right = zone end
          </p>
          <BlendRow label="Ink → Sienna" value={config.blends.inkToSienna} onChange={v => setBlend('inkToSienna', v)} />
          <BlendRow label="→ Orange"     value={config.blends.toOrange}    onChange={v => setBlend('toOrange', v)} />
          <BlendRow label="→ Ink"        value={config.blends.backToInk}   onChange={v => setBlend('backToInk', v)} />
          <BlendRow label="→ Black"      value={config.blends.toBlack}     onChange={v => setBlend('toBlack', v)} />

          {/* RIPPLE */}
          <SectionLabel>Ripple · Lens refraction</SectionLabel>
          <Row label="Enable">
            <Toggle value={config.ripple.enabled} onChange={v => setRipple({ enabled: v })} />
          </Row>
          <Row label="Blend">
            <BlendMode value={config.ripple.blendMode} onChange={v => setRipple({ blendMode: v })} />
          </Row>
          <Row label="Speed">
            <Slider value={config.ripple.speed} min={0.1} max={10} step={0.1} onChange={v => setRipple({ speed: v })} />
          </Row>
          <Row label="Frequency">
            <Slider value={config.ripple.frequency} min={2} max={50} step={0.5} onChange={v => setRipple({ frequency: v })} />
          </Row>
          <Row label="Amplitude">
            <Slider value={config.ripple.amplitude} min={0} max={0.12} step={0.001} onChange={v => setRipple({ amplitude: v })} />
          </Row>
          <Row label="Lens glare">
            <Slider value={config.ripple.lensGlare} min={0} max={3} step={0.05} onChange={v => setRipple({ lensGlare: v })} />
          </Row>
          <Row label="Chromatic">
            <Slider value={config.ripple.chromatic} min={0} max={1} onChange={v => setRipple({ chromatic: v })} />
          </Row>
          <Row label="Scale">
            <Slider value={config.ripple.scale} min={0.1} max={5} step={0.05} onChange={v => setRipple({ scale: v })} />
          </Row>

          {/* RAYS */}
          <SectionLabel>Rays · Glow</SectionLabel>
          <Row label="Enable">
            <Toggle value={config.rays.enabled} onChange={v => setRays({ enabled: v })} />
          </Row>
          <Row label="Blend">
            <BlendMode value={config.rays.blendMode} onChange={v => setRays({ blendMode: v })} />
          </Row>
          <Row label="Intensity">
            <Slider value={config.rays.intensity} min={0} max={1.5} step={0.01} onChange={v => setRays({ intensity: v })} />
          </Row>
          <Row label="Count">
            <IntSlider value={config.rays.count} min={1} max={24} onChange={v => setRays({ count: v })} />
          </Row>
          <Row label="Speed">
            <Slider value={config.rays.speed} min={0} max={0.8} step={0.005} onChange={v => setRays({ speed: v })} />
          </Row>
          <Row label="Sharpness">
            <Slider value={config.rays.sharpness} min={1} max={60} step={0.5} onChange={v => setRays({ sharpness: v })} />
          </Row>
          <Row label="Noise">
            <Slider value={config.rays.noise} min={0} max={1} onChange={v => setRays({ noise: v })} />
          </Row>
          <Row label="Falloff">
            <Slider value={config.rays.falloff} min={0.2} max={12} step={0.1} onChange={v => setRays({ falloff: v })} />
          </Row>
          <Row label="Core">
            <Slider value={config.rays.core} min={0} max={3} step={0.05} onChange={v => setRays({ core: v })} />
          </Row>
          <Row label="Origin X">
            <Slider value={config.rays.originX} min={-0.5} max={1.5} onChange={v => setRays({ originX: v })} />
          </Row>
          <Row label="Origin Y">
            <Slider value={config.rays.originY} min={-0.5} max={1.5} onChange={v => setRays({ originY: v })} />
          </Row>
          <ColorSwatch label="Ray colour" value={config.rays.color} onChange={v => setRays({ color: v })} />
          <Row label="Scale">
            <Slider value={config.rays.scale} min={0.1} max={5} step={0.05} onChange={v => setRays({ scale: v })} />
          </Row>

        </div>

        {/* ── Save to file footer ───────────────────────────────────────── */}
        <div style={{
          padding: '10px 14px',
          borderTop: `1px solid ${D.border}`,
          background: 'rgba(0,0,0,0.2)',
        }}>
          <button
            onClick={handleSaveToFile}
            style={{
              width: '100%', padding: '9px 0',
              fontFamily: D.font, fontSize: 11, fontWeight: 600,
              letterSpacing: '0.06em', textTransform: 'uppercase',
              cursor: 'pointer', borderRadius: D.radius,
              background:  saved ? 'rgba(76,175,80,0.18)' : D.accentDim,
              border:      `1px solid ${saved ? D.green : D.accent}`,
              color:       saved ? D.green : D.text,
              transition:  `background 0.3s, border-color 0.3s, color 0.3s`,
            }}
          >
            {saved ? '✓  Saved — replace gradient.config.ts' : '💾  Save to file'}
          </button>
          <p style={{
            fontFamily: D.font, fontSize: 9, color: D.muted,
            marginTop: 7, lineHeight: 1.6, textAlign: 'center',
          }}>
            Downloads <code style={{ color: D.text }}>gradient.config.ts</code> · drop it into{' '}
            <code style={{ color: D.text }}>src/components/ui/</code> · Vite reloads
          </p>
        </div>

      </div>
    </>
  )
}
