// ─── GRADIENT PRESET — SixDX ─────────────────────────────────────────────────
// Auto-generated by the [GL] control panel · 04 May 2026
//
// To update:
//   1. Open the project in the browser  (npm run dev)
//   2. Click the [GL] button in the bottom-right corner
//   3. Dial in your effects
//   4. Click "💾 Save to file" inside the panel
//   5. A file called  gradient.config.ts  will download
//   6. Replace  src/components/ui/gradient.config.ts  with the downloaded file
//   7. Vite hot-reloads — your settings are now the project defaults
// ─────────────────────────────────────────────────────────────────────────────
import type { GradientConfig } from './GradientCanvas'

export const PRESET_GRADIENT_CONFIG: GradientConfig = {
  "speed": 0.2,
  "warpScale": 1.1,
  "grain": 0.049,
  "vignette": 0,
  "colors": {
    "ink": "#1C0B05",
    "orange": "#CC4D22",
    "sienna": "#74331D",
    "black": "#030101"
  },
  "blends": {
    "inkToSienna": [
      0.39,
      0.69
    ],
    "toOrange": [
      0.43,
      0.6
    ],
    "backToInk": [
      0.55,
      0.75
    ],
    "toBlack": [
      0.61,
      1
    ]
  },
  "ripple": {
    "enabled": true,
    "speed": 1.3,
    "frequency": 3,
    "amplitude": 0.12,
    "lensGlare": 0.05,
    "chromatic": 1,
    "blendMode": 0,
    "scale": 0.45
  },
  "rays": {
    "enabled": true,
    "intensity": 1.13,
    "count": 6,
    "speed": 0.675,
    "originX": 0.48,
    "originY": 1.18,
    "sharpness": 44.5,
    "color": "#ffa681",
    "noise": 0.73,
    "falloff": 10.8,
    "core": 2.2,
    "blendMode": 1,
    "scale": 3.9
  }
}
